</script>
<?php
	include('snippets/sidebars/STAB57.php');
	include('snippets/STAB57/people/TAs/LdT.html');
	include('snippets/STAB57/people/TAs/Bo_Chen.html');
	include('snippets/STAB57/people/TAs/Shahriar_Shams.html');
	include('snippets/STAB57/people/TAs/Xiaolu_Xiong.html');
	include('snippets/STAB57/people/TAs/Xiucai_Ding.html');
?>
